In [6]:
import pandas as pd
import getpass
import requests
import json
import curl
from bs4 import BeautifulSoup

In [9]:
# your code here
url = 'http://api.dataatwork.org/v1//jobs/autocomplete?ends_with=Data analyst'
da_request = requests.get(url)
da_json = da_request.json()
da_df = pd.json_normalize(da_json)

# To print the JSON response in a pretty way

In [10]:
da_df

,uuid,suggestion,normalized_job_title,parent_uuid
0,f1fc61f279e3ad14863e582ca6fdc473,Clinical Data Analyst,clinical data analyst,0b9dd32a367f4562ec77b993053d1910
1,65b92572bca68ff9c49c930749fa348c,LiDAR Data Analyst,lidar data analyst,fc4ee61f733cdbb2c04f4693075a202d
2,6cf4d336112984368f83181ac5ffe948,Health Data Analyst,health data analyst,db06efbaa9cb31d42e02c047ffb0a15a
3,7acaed29536648e45ea2b82d45047fcf,Medical Data Analyst,medical data analyst,db06efbaa9cb31d42e02c047ffb0a15a
4,25fe195cbf915c0824fa6c44e6d0008c,Maintenance Data Analyst,maintenance data analyst,9b44dbc6767274d8b3a820e133803d00
5,eb3d789747d52df803ce63fe37bf53e9,Data Analyst,data analyst,325e2251e20170928426473156bd3c48

In [11]:
url = 'http://api.dataatwork.org/v1/jobs/eb3d789747d52df803ce63fe37bf53e9/related_skills'
skills = requests.get(url)
skills_json = skills.json()
skills_df = pd.json_normalize(skills_json["skills"])

In [14]:
skills_df.loc[]

,skill_uuid,skill_name,skill_type,description,normalized_skill_name,importance,level
0,e72f8046dc4d704b6d1ca41dada93853,mathematical reasoning,ability,the ability to choose the right mathematical m...,mathematical reasoning,4.62,4.88
1,500018df958f2b9f8b387cf5637a0a04,english language,knowledge,knowledge of the structure and content of the ...,english language,4.05,4.40
2,19bec38cfa59f6542132b1ab155438c7,written comprehension,ability,the ability to read and understand information...,written comprehension,4.00,4.00
3,809bcc13fd9a8517d2abefa4f15ed113,number facility,ability,"the ability to add, subtract, multiply, or div...",number facility,4.00,4.62
4,6ae28a55456b101be8261e5dee44cd3e,mathematics,skill,using mathematics to solve problems.,mathematics,3.98,5.32
5,0194023051cb666af3d2c4761d894957,oral comprehension,ability,the ability to listen to and understand inform...,oral comprehension,3.88,4.12
6,01f0f8544779b7139f0152f2af679983,written expression,ability,the ability to communicate information and ide...,written expression,3.88,3.88
7,b3cb1294905e001d3d611bff1de3962c,computers and electronics,knowledge,"knowledge of circuit boards, processors, chips...",computers and electronics,3.85,5.04
8,2c77c703bd66e104c78b1392c3203362,reading comprehension,skill,understanding written sentences and paragraphs...,reading comprehension,3.75,4.00
9,20784bf09c9fe614603ad635e6093ede,critical thinking,skill,using logic and reasoning to identify the stre...,critical thinking,3.75,3.88

In [35]:
skills_df.to_excel("da_skills.xlsx")